resources:
- repo: self
queue:
  name: Default
steps:
- task: PowerShell@2
  displayName: 'PowerShell Script'
  inputs:

    filePath: Helloworld.ps1


- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: Helloworld.ps1



